### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by daftpunkcodeman** [MegaOwIer/JumpMouth#2]
你好！俺今天vscode遇到了一个您先前遇到过的问题：
https://github.com/microsoft/vscode-cpptools/issues/4140
但是俺实在不明白怎么去解决，可以方便聊一下吗！！万分感谢

**Comment by MegaOwIer** [comment]
az 抱歉隔了快一年才看到......
我当时的解决方法是关掉 Windows 设置中的 `Beta: Use Unicode UTF-8 for worldwide language support` 选项。这玩意大概在 Windows 语言和地区相关设置的某一个犄角旮旯里。
